#!/bin/bash
#
# place this file in /etc/init.d/gollum-server
# change the file permission to executable:
# $ sudo chmod +x /etc/init.d/gollum-server
# add it to default run level
# $ sudo update-rc.d gollum-server defaults

######################################################
### Configuration
######################################################
PID="/var/run/gollum-server.pid"

# The location of the git repository
WIKI="/home/pi/plp/repo"

# The location if the gollum executable
DAEMON="/usr/local/bin/gollum"
# --port     : the port number gollum should listen on
# --config   : the location of your config file
DAEMON_OPT="--config /home/pi/plp/config.rb"
# The user the git repository belongs to
USER="pi"
# The group the git repository belongs to
GROUP="pi"


######################################################
### Script
######################################################

case "$1" in
  start)
    echo "Starting Gollum"
    start-stop-daemon --start --quiet -b -m -p $PID --chuid $USER:$GROUP --chdir $WIKI --exec $DAEMON -- $DAEMON_OPT
  ;;
  stop)
    echo "Stopping Gollum"
    start-stop-daemon --stop --quiet --pidfile $PID
    rm -f $PID
  ;;
  *)
    echo "Usage: service gollum-server {start|stop}"
    exit 1
  ;;
esac
exit 0
